const fs = require('fs');

function fixClosingTags(filename) {
    let content = fs.readFileSync(filename, 'utf8');

    // For any section where there's an extra </div>
    // The pattern generated by esbuild error is:
    // 575|              </div>
    // 576|              </div>
    // 577|                </div>
    // 578|              </section>
    
    // So we can replace:
    // </div>\n              </div>\n                </div>\n              </section>
    // with:
    // </div>\n              </div>\n              </section>
    
    content = content.replace(/<\/div>\s*<\/div>\s*<\/div>\s*<\/section>/g, '</div>\n              </div>\n            </section>');
    
    fs.writeFileSync(filename, content);
}

fixClosingTags('pages/OtelCozumlerimizPage.tsx');
fixClosingTags('pages/OtelProjelerimizPage.tsx');
